[pytest]
testpaths = tests
addopts = -ra --strict-config --strict-markers
filterwarnings =
    error
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning:starlette\.testclient
